# Generated by Django 4.0.3 on 2022-03-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_image_post_photo_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='dog',
        ),
    ]
